apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-interface
  template:
    metadata:
      labels:
        app: chatbot-interface
    spec:
      serviceAccountName: focusing-manager-serviceaccount
      containers:
      - name: chatbot-interface
        image: gravitate-registry.cr.de-fra.ionos.com/chatbot-interface:latest
        imagePullPolicy: Always
        env:
        - name: CHATBOT_URL
          value: "http://chat-with-epi:80"
        - name: FHIR_EPI_URL
          value: "https://gravitate-health.lst.tfo.upm.es/epi/api/fhir"
        - name: CHATBOT_LABEL_SELECTOR
          value: "eu.gravitate-health.fosps.chatbot=true"
        - name: ENVIRONMENT
          value: prod
        resources: {}
      restartPolicy: Always
status: {}
