# Require valid JWT for apps that have the label "istioRequireAuthentication: true"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: chatbot-interface-authpolicy
spec:
  selector:
    matchLabels:
      app: chatbot-interface
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            methods: ["POST"]
            paths: ["/chat", "/chat/"]
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/chatbots"]
